---
  - name: Instalacao nginx e php para funcionamento do WP

  - name: Configuracao do vhost nginx
    template:
      src: vhost.nginx.conf.j2
      dest: /etc/nginx/sites-enabled/default

  - name: Baixando o projeto do wordpress e descompactando
    ansible.builtin.unarchive:
      src: https://wordpress.org/latest.zip
      dest: /var/www/html/
      remote_src: yes

  - name: Alterando o arquivo wp-config
    template: 
      src: wp-config.php.j2
      dest: /var/www/html/wordpress/wp-config.php

  - name: Alterando permissao do /var/www/html/wordpress
    ansible.builtin.file:
      path: /var/www/html/wordpress
      owner: www-data
      group: www-data
      mode: '0755'
  
  - name: Restart nginx
    service:
      name: nginx
      state: restarted